/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentrecord;

/**
 *
 * @author hp
 */import java.sql.*;
import javax.swing.table.DefaultTableModel;
import studentrecord.MainFrame;
public class List extends javax.swing.JDialog {
MainFrame frame;
    /**
     * Creates new form List
     */String course,branch;
    public List(java.awt.Frame parent, boolean modal,String c,String b,MainFrame f) {
        super(parent, modal);course=c;branch=b;frame=f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrollment", "Name", "Branch", "Semester", "College", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("1st Year");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jRadioButton2.setText("2nd Year");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jRadioButton3.setText("3rd Year");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jRadioButton4.setText("4th Year");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIIST", "NIRT" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("________________________List  of  Students ___________________________");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecord/NIIST.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Found :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      int x=0;
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
        String year="3rd",college;
        int r=jTable1.getRowCount();
      for(int i=0;i<r;i++)
          d.removeRow(0);
        if(branch.equals("CS"))
            branch=branch+"E";
      college=jComboBox1.getSelectedItem().toString();
      
        if(jRadioButton1.isSelected())
            year="1st";
        else if(jRadioButton1.isSelected())
            year="2nd";
        else if(jRadioButton1.isSelected())
            year="3rd";
        else if(jRadioButton1.isSelected())
            year="4th";
        
        try {Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521",Oracle.user,Oracle.pass);
            System.out.println("Success con...");
            Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from niist  where year='"+year+"' and branch='"+branch+"' and college='"+college+"' and course='"+course+"'" );
           while(rs.next())
                   {x++;
                       Object o[]={rs.getString(2),rs.getString(3),rs.getString("branch")+"",rs.getInt("sem"),rs.getString("college"),rs.getLong("mobile")};
                       d.addRow(o);
                   }st.close();jLabel4.setText(x+".");
            System.out.println(course+" "+branch+" "+year+" "+college);
        } catch (Exception e) {
        }  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
     int x=0;
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
        int r=jTable1.getRowCount();
      for(int i=0;i<r;i++)
          d.removeRow(0);
        
        String year="3rd",college;
        if(branch.equals("CS"))
            branch=branch+"E";
      college=jComboBox1.getSelectedItem().toString();
        
        try {Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521",Oracle.user,Oracle.pass);
            System.out.println("Success con...");
            Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from niist  where year='"+year+"' and branch='"+branch+"' and college='"+college+"' and course='"+course+"'" );
             // ResultSet trs=st.executeQuery("select * from niist  where year='"+year+"' and branch='"+branch+"' and college='"+college+"' and course='"+course+"'" );
        
           while(rs.next())
                   {x++;
                       Object o[]={rs.getString(2),rs.getString(3),rs.getString("branch")+"",rs.getInt("sem"),rs.getString("college"),rs.getLong("mobile")};
                       d.addRow(o);
                   }st.close();jLabel4.setText(x+".");
            System.out.println(course+" "+branch+" "+year+" "+college);
        } catch (Exception e) {
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
      int x=0;
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
          int r=jTable1.getRowCount();
      for(int i=0;i<r;i++)
          d.removeRow(0);
        String year="4th",college;
        if(branch.equals("CS"))
            branch=branch+"E";
      college=jComboBox1.getSelectedItem().toString();
        
        try {Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521",Oracle.user,Oracle.pass);
            System.out.println("Success con...");
            Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from niist  where year='"+year+"' and branch='"+branch+"' and college='"+college+"' and course='"+course+"'" );
           while(rs.next())
                   {x++;
                       Object o[]={rs.getString(2),rs.getString(3),rs.getString("branch")+"",rs.getInt("sem"),rs.getString("college"),rs.getLong("mobile")};
                       d.addRow(o);
                   }st.close();jLabel4.setText(x+".");
            System.out.println(course+" "+branch+" "+year+" "+college);
        } catch (Exception e) {
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       int x=0;
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
          int r=jTable1.getRowCount();
      for(int i=0;i<r;i++)
          d.removeRow(0);
        String year="2nd",college;
        if(branch.equals("CS"))
            branch=branch+"E";
      college=jComboBox1.getSelectedItem().toString();
        
        try {Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521",Oracle.user,Oracle.pass);
            System.out.println("Success con...");
            Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from niist  where year='"+year+"' and branch='"+branch+"' and college='"+college+"' and course='"+course+"'" );
           while(rs.next())
                   {x++;
                       Object o[]={rs.getString(2),rs.getString(3),rs.getString("branch")+"",rs.getInt("sem"),rs.getString("college"),rs.getLong("mobile")};
                       d.addRow(o);
                   }st.close();jLabel4.setText(x+".");
            System.out.println(course+" "+branch+" "+year+" "+college);
        } catch (Exception e) {
        } // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       int x=0;
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
          int r=jTable1.getRowCount();
      for(int i=0;i<r;i++)
          d.removeRow(0);
        String year="1st",college;
        if(branch.equals("CS"))
            branch=branch+"E";
      college=jComboBox1.getSelectedItem().toString();
        
        try {Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521",Oracle.user,Oracle.pass);
            System.out.println("Success con...");
            Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from niist  where year='"+year+"' and branch='"+branch+"' and college='"+college+"' and course='"+course+"'" );
           while(rs.next())
                   {x++;
                       Object o[]={rs.getString(2),rs.getString(3),rs.getString("branch")+"",rs.getInt("sem"),rs.getString("college"),rs.getLong("mobile")};
                       d.addRow(o);
                   }st.close();jLabel4.setText(x+".");
            System.out.println(course+" "+branch+" "+year+" "+college);
        } catch (Exception e) {
        } // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(evt.getClickCount()==2)
        { int x=jTable1.getSelectedRow();
            String en=    jTable1.getValueAt(x,0).toString();
            new Information(frame,true,en).setVisible(true);
            System.out.println(en);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              /*  List dialog = new List(new javax.swing.JFrame(), true,"B.tech","CS");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
